[template]
src = "groupengine.ini.tmpl"
dest = "/etc/groupengine.ini"
keys = [
    "/fc/status/token",
    "/fc/statsd/server",
    "/fc/statsd/port",
    "/fc/statsd/prefix",
    "/fc/oauth/realm",
    "/fc/cassandra/contactpoints",
    "/fc/cassandra/keyspace",
    "/fc/cassandra/username",
    "/fc/cassandra/password",
    "/fc/logtimings",
    "/fc/ratelimit/maxshare",
    "/fc/ratelimit/maxrate",
    "/fc/ratelimit/maxburstsize",
    "/fc/groups/timeout",
    "/fc/fs/baseurl",
    "/fc/fs/username",
    "/fc/fs/password",
]
