cassandra:
  image: cassandra:2.1
  ports:
    - "9042:9042"
dataportenschemas:
  image: uninett-docker-uninett.bintray.io/feideconnect/dataportenschemas
  links:
    - cassandra:cassandra
  environment:
    - CASSANDRA_NODE=cassandra
    - CASSANDRA_KEYSPACE=test_coreapis
    - TESTDATA=true
