cassandra:
  image: cassandra:2.2
  ports:
    - "9042:9042"
dataportenschemas:
  image: registry.uninett.no/public/dataporten-cassandra-schemas
  links:
    - cassandra:cassandra
  environment:
    - CASSANDRA_NODE=cassandra
    - CASSANDRA_KEYSPACE=test_coreapis
    - TESTDATA=true
  command: up
