cassandra:
  image: cassandra:2.2
dataportenschemas:
  image: registry.uninett.no/public/dataporten-cassandra-schemas
  links:
    - cassandra:cassandra
  environment:
    - CASSANDRA_NODE=cassandra
    - CASSANDRA_KEYSPACE=test_coreapis
    - TESTDATA=true
  command: up
coreapis:
  build: .
  dockerfile: Dockerfile-tests
  volumes:
    - .:/app
  links:
    - cassandra:cassandra
  environment:
    - DP_CASSANDRA_TEST_NODE=cassandra
    - DP_CASSANDRA_TEST_KEYSPACE=test_coreapis
