[template]
src = "core-apis.ini.tmpl"
dest = "/etc/core-apis.ini"
keys = [
    "/fc/status/token",
    "/fc/statsd/server",
    "/fc/statsd/port",
    "/fc/statsd/prefix",
    "/fc/oauth/realm",
    "/fc/cassandra/contactpoints",
    "/fc/cassandra/keyspace",
    "/fc/cassandra/username",
    "/fc/cassandra/password",
    "/fc/logtimings",
    "/fc/profiletokensecret",
    "/fc/ps/cachekeyspace",
    "/fc/adhocgroupadm/maxaddmembers",
    "/fc/ratelimit/maxshare",
    "/fc/ratelimit/maxrate",
    "/fc/ratelimit/maxburstsize",
    "/fc/orgadmin/maxrows",
]
